public class TableDeMultiplication_s_2 {
    public static final String ANSI_ROUGE = "\u001B[31m";
    public static final String ANSI_VERT = "\u001B[32m";
    public static final String ANSI_JAUNE = "\u001B[33m";
    public static final String ANSI_BLEU = "\u001B[34m";
    public static final String ANSI_BVIOLET = "\u001B[35m";
    public static final String ANSI_CYAN = "\u001B[36m";
    public static final String ANSI_BLANC = "\u001B[37m";
    public static final String ANSI_RESET = "\u001B[0m";
    public static void main(String[] args) {
        System.out.println(ANSI_BLEU+"\t=========LA TABLE DE MULTIPLICATION  ========= "+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 1 = " + (1*1) + "\t\t2 x 1 = " + (2*1)+ "\t\t3 x 1 = " + (3*1)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 2 = " + (1*2) + "\t\t2 x 2 = " + (2*2)+ "\t\t3 x 2 = " + (3*2)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 3 = " + (1*3) + "\t\t2 x 3 = " + (2*3)+ "\t\t3 x 3 = " + (3*3)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 4 = " + (1*4) + "\t\t2 x 4 = " + (2*4)+ "\t\t3 x 4 = " + (3*4)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 5 = " + (1*5) + "\t\t2 x 5 = " + (2*5)+ "\t\t3 x 5 = " + (3*5)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 6 = " + (1*6) + "\t\t2 x 6 = " + (2*6)+ "\t\t3 x 6 = " + (3*6)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 7 = " + (1*7) + "\t\t2 x 7 = " + (2*7)+ "\t\t3 x 7 = " + (3*7)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 8 = " + (1*8) + "\t\t2 x 8 = " + (2*8)+ "\t\t3 x 8 = " + (3*8)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 9 = " + (1*9) + "\t\t2 x 9 = " + (2*9)+ "\t\t3 x 9 = " + (3*9)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 10 = " + (1*10) + "\t\t2 x 10 = " + (2*10)+ "\t\t3 x 10 = " + (3*10)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 11 = " + (1*11) + "\t\t2 x 11 = " + (2*11)+ "\t\t3 x 11 = " + (3*11)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_VERT+"\t|\t1 x 12 = " + (1*12) + "\t\t2 x 12 = " + (2*12)+ "\t\t3 x 12 = " + (3*12)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_BLEU+"\t=============================================== "+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 1 = " + (4*1)+ "\t\t5 x 1 = " + (5*1)+ "\t\t6 x 1 = " + (6*1)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 2 = " + (4*2)+ "\t\t5 x 2 = " + (5*2)+ "\t\t6 x 2 = " + (6*2)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 3 = " + (4*3)+ "\t\t5 x 3 = " + (5*3)+ "\t\t6 x 3 = " + (6*3)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 4 = " + (4*4)+ "\t\t5 x 4 = " + (5*4)+ "\t\t6 x 4 = " + (6*4)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 5 = " + (4*5)+ "\t\t5 x 5 = " + (5*5)+ "\t\t6 x 5 = " + (6*5)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 6 = " + (4*6)+ "\t\t5 x 6 = " + (5*6)+ "\t\t6 x 6 = " + (6*6)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 7 = " + (4*7)+ "\t\t5 x 7 = " + (5*7)+ "\t\t6 x 7 = " + (6*7)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 8 = " + (4*8)+ "\t\t5 x 8 = " + (5*8)+ "\t\t6 x 8 = " + (6*8)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 9 = " + (4*9)+ "\t\t5 x 9 = " + (5*9)+ "\t\t6 x 9 = " + (6*9)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 10 = " + (4*10)+ "\t\t5 x 10 = " + (5*10)+ "\t\t6 x 10 = " + (6*10)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 11 = " + (4*11)+ "\t\t5 x 11 = " + (5*11)+ "\t\t6 x 11 = " + (6*11)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_ROUGE+"\t|\t4 x 12 = " + (4*12)+ "\t\t5 x 12 = " + (5*12)+ "\t\t6 x 12 = " + (6*12)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_BLEU+"\t================================================= "+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 1 = " + (7*1)+ "\t\t8 x 1 = " + (8*1)+ "\t\t9 x 1 = " + (9*1)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 2 = " + (7*2)+ "\t\t8 x 2 = " + (8*2)+ "\t\t9 x 2 = " + (9*2)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 3 = " + (7*3)+ "\t\t8 x 3 = " + (8*3)+ "\t\t9 x 3 = " + (9*3)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 4 = " + (7*4)+ "\t\t8 x 4 = " + (8*4)+ "\t\t9 x 4 = " + (9*4)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 5 = " + (7*5)+ "\t\t8 x 5 = " + (8*5)+ "\t\t9 x 5 = " + (9*5)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 6 = " + (7*6)+ "\t\t8 x 6 = " + (8*6)+ "\t\t9 x 6 = " + (9*6)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 7 = " + (7*7)+ "\t\t8 x 7 = " + (8*7)+ "\t\t9 x 7 = " + (9*7)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 8 = " + (7*8)+ "\t\t8 x 8 = " + (8*8)+ "\t\t9 x 8 = " + (9*8)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 9 = " + (7*9)+ "\t\t8 x 9 = " + (8*9)+ "\t\t9 x 9 = " + (9*9)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 10 = " + (7*10)+ "\t\t8 x 10 = " + (8*10)+ "\t\t9 x 10 = " + (9*10)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 11 = " + (7*11)+ "\t\t8 x 11 = " + (8*11)+ "\t\t9 x 11 = " + (9*11)+"\t|"+ANSI_RESET);
        System.out.println(ANSI_JAUNE+ "\t|\t7 x 12 = " + (7*12)+ "\t\t8 x 12 = " + (8*12)+ "\t\t9 x 12 = " + (9*12)+"|"+ANSI_RESET);
        System.out.println("\t================================================= "+ANSI_RESET);
    }
}
